 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace GameRoomC2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestUserReady = (Nettention.Proud.RmiID)7000+1;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestUserReady,
		};
	}
}






				 
