




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace GameRoomS2C
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool NotifyUserConnected(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String nickname, bool isReady)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.NotifyUserConnected;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, nickname);
		Nettention.Proud.Marshaler.Write(__msg, isReady);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_NotifyUserConnected, Common.NotifyUserConnected);
}

public bool NotifyUserConnected(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String nickname, bool isReady)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.NotifyUserConnected;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, nickname);
Nettention.Proud.Marshaler.Write(__msg, isReady);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_NotifyUserConnected, Common.NotifyUserConnected);
}
public bool NotifyUserDisconnected(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String nickname)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.NotifyUserDisconnected;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, nickname);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_NotifyUserDisconnected, Common.NotifyUserDisconnected);
}

public bool NotifyUserDisconnected(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String nickname)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.NotifyUserDisconnected;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, nickname);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_NotifyUserDisconnected, Common.NotifyUserDisconnected);
}
public bool NotifyUserReady(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String nickname)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.NotifyUserReady;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, nickname);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_NotifyUserReady, Common.NotifyUserReady);
}

public bool NotifyUserReady(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String nickname)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.NotifyUserReady;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, nickname);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_NotifyUserReady, Common.NotifyUserReady);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_NotifyUserConnected="NotifyUserConnected";
public const string RmiName_NotifyUserDisconnected="NotifyUserDisconnected";
public const string RmiName_NotifyUserReady="NotifyUserReady";
       
public const string RmiName_First = RmiName_NotifyUserConnected;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_NotifyUserConnected="";
public const string RmiName_NotifyUserDisconnected="";
public const string RmiName_NotifyUserReady="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

