 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace GameRoomS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID NotifyUserConnected = (Nettention.Proud.RmiID)8000+1;
			public const Nettention.Proud.RmiID NotifyUserDisconnected = (Nettention.Proud.RmiID)8000+2;
			public const Nettention.Proud.RmiID NotifyUserReady = (Nettention.Proud.RmiID)8000+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			NotifyUserConnected,
			NotifyUserDisconnected,
			NotifyUserReady,
		};
	}
}






				 
