




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace InGameC2S
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
       
public const string RmiName_First = "";
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

