 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace InGameC2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
		};
	}
}






				 
